//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Linq;
using System.Collections.Generic;

namespace GameObjects
{
	public class PlayerCharacter : ICharacter, ISavable
	{
		#region Private Properties

		private float _inventoryWeight { get {
			float weight = 0.0f;
			foreach(IBaseItem item in Inventory) {
				weight += item.Weight;
			}
				return weight;
		}}

		#endregion


		#region Properties

		public CharacterStatus Status { get; private set; }
		public List<IBaseItem> Inventory { get; private set; }
		public Armor Armor { get; private set; }
		public Weapon Weapon { get; private set; }

		public float CurrentEncumberance { get {
			return _inventoryWeight + Armor.Weight + Weapon.Weight;
		}}

		#endregion


		#region Constructor

		public PlayerCharacter (XElement characterXML)
		{

		}

		#endregion


		#region Methods

		public AddToInventoryResults AddItemToInventory(IBaseItem item)
		{
			if(Inventory.Count == Armor.Pockets)
				return AddToInventoryResults.NotEnoughPockets;
			else if(CurrentEncumberance + item.Weight > Status.MaxEncumberance)
				return AddToInventoryResults.TooHeavy;
			else {
				Inventory.Add(item);
			}

			return AddToInventoryResults.Success;
		}	

		public XElement Save()
		{
			return null;
		}

		#endregion
	}
}

