//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace GameObjects
{
	public class Coordinates
	{
		public readonly int X;
		public readonly int Y;

		public Coordinates (int x, int y)
		{
			X = x;
			Y = y;
		}
	}
}

