//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace GameObjects
{
	public static class Constants
	{
		public static string XMLName { get { return "Name"; } }
        public static string XMLRequiredClass { get { return "RequiredClass"; } }
		public static string XMLMaxItemHealth { get { return "MaxItemHealth"; } }
		public static string XMLCurrentItemHealth { get { return "CurrentItemHealth"; } }
		public static string XMLStrengthRequirement { get { return "StrengthRequirement"; } }
		public static string XMLDexterityRequirement { get { return "DexterityRequirement"; } }
		public static string XMLRootModifier { get { return "RootModifier"; } }
		public static string XMLWeight { get { return "Weight"; } }
		public static string XMLEquipmentTypesStats { get { return "EquipmentTypesStats"; } }
		public static string XMLEquipment { get { return "Equipment"; } }
		public static string XMLArmorType { get { return "ArmorType"; } }
		public static string XMLArmor { get { return "Armor"; } }
		public static string XMLWeaponType { get { return "WeaponType"; } }
		public static string XMLWeapon { get { return "Weapon"; } }
		public static string XMLPockets { get { return "Pockets"; } }
		public static string XMLCharacterStatus { get { return "CharacterStatus"; } }
		public static string XMLInventory { get { return "Inventory"; } }
		public static string XMLConsumable { get { return "Consumable"; } }
		public static string XMLCharacter{ get { return "Character"; } }
		public static string XMLSpritesFolder{ get { return "Sprites"; } }
        public static string XMLDescription { get { return "Description"; } }
	}
}

