//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Linq;

namespace GameObjects
{
	public class Armor : BaseEquipment, IBaseItem
	{
		#region Properties
		
		public int Pockets { get; set; }

        public ArmorTypes ArmorType { get; set; }
		
		#endregion


		#region Read-only Properties
		

		
		#endregion
		
		
		#region Constructors
		
        public Armor() : base()
        {
            ArmorType = ArmorTypes.Chestplate;
        }

		public Armor(XElement armorXML): base(armorXML.Element(Constants.XMLEquipment))
		{
			ArmorType = (ArmorTypes)System.Enum.Parse (typeof(ArmorTypes), armorXML.Attribute(Constants.XMLArmorType).Value);
			Pockets = int.Parse(armorXML.Attribute(Constants.XMLPockets).Value);
		}
		
		#endregion
		
		
		#region Methods	
		
		public XElement Save()
		{
			XElement armorData = new XElement (Constants.XMLArmor, 
			                                    new XAttribute (Constants.XMLArmorType, ArmorType.ToString ()),
			                                    new XAttribute (Constants.XMLPockets, Pockets));
			
			armorData.Add(base.Save ());
			
			return armorData;
		}	
		
		#endregion
	}
}

