//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Linq;

namespace GameObjects
{
	public class Armor : BaseEquipment, ISavable, IBaseItem
	{
		#region Properties
		
		public readonly ArmorTypes ArmorType;
		
		#endregion
		
		
		#region Constructors
		
		public Armor(XElement weaponXML): base(weaponXML.Element("Equipment"))
		{
			ArmorType = (ArmorTypes)System.Enum.Parse (typeof(ArmorTypes), weaponXML.Attribute("ArmorType").Value);
		}
		
		#endregion
		
		
		#region Methods	
		
		public XElement Save()
		{
			XElement armorData = new XElement ("Armor", 
			                                    new XAttribute ("ArmorType", ArmorType.ToString ()));
			
			armorData.Add(base.Save ());
			
			return armorData;
		}	
		
		#endregion
	}
}

