//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Linq;

namespace GameObjects
{
	public class Consumable : IBaseItem
	{
		public string Name { get; private set; }
		public float Weight { get; private set; }
		public string SpritesFolder { get; private set; }

		public Consumable (XElement consumableXML)
		{
			Name = consumableXML.Attribute(Constants.XMLName).Value;
			Weight = int.Parse(consumableXML.Attribute(Constants.XMLWeight).Value);
			SpritesFolder = consumableXML.Attribute(Constants.XMLSpritesFolder).Value;
		}

		public XElement Save()
		{
			XElement consumableData = new XElement (Constants.XMLConsumable, 
			                                   new XAttribute (Constants.XMLName, Name),
			                                   new XAttribute (Constants.XMLWeight, Weight),
		                                       new XAttribute (Constants.XMLSpritesFolder, SpritesFolder));

			return consumableData;
		}
	}
}

