//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Linq;

namespace GameObjects
{
	public class Consumable : IBaseItem
	{
		public string Name { get; private set; }
		public float Weight { get; private set; }

		public Consumable (XElement consumableXML)
		{

		}

		public XElement Save()
		{
			return null;
		}
	}
}

